mapping:
  mixer:
    - cc: 0
      reverse: true
      min: 0
      max: 64
      filename:
        - destiny2.exe
        - amidevil.exe
        - noita.exe
    - cc: 1
      filename:
      - chrome.exe
      - edge.exe
    - cc: 2
      filename:
      - mstsc.exe
    # - cc: 3
    #   special:
    #    - output
    #    - current
    # - cc: 4
    #   special:
    #     - system
    - cc: 5
      device:
        - Headphones
    - cc: 6
      filename:
        - discord.exe
        - zoom.exe
    - cc: 7
      filename:
        - YouTube Music Desktop App.exe
  shell:
    - cc: 71
      command:
        - dir

midi_devicename: nanoKONTROL2
