# Rename this to config.yml to use with the main application, or specify the updated name when opening.
mapping:
  mixer:
    - cc: 0
      filename: game.exe
      reverse: true
      min: 0
      max: 64

    - cc: 1
      filename:
        - chrome.exe
        - firefox.exe

    - cc: 2
      filename: mstsc.exe

    - cc: 3
      special: output

    - cc: 4
      special: system

    - cc: 5
      device: Headphones

    - cc: 6
      filename: discord.exe

    - cc: 7
      filename: YouTube Music Desktop App.exe
  shell:
    - cc: 39
      command: ls

    - cc: 55
      command: dir

midi_devicename: nanoKONTROL2
